repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy-backend
        name: mypy backend
        entry: poetry -C backend run mypy --config-file backend/pyproject.toml backend/src/
        language: system
        pass_filenames: false
      - id: mypy-cli
        name: mypy cli
        entry: poetry -C cli run mypy --config-file cli/pyproject.toml cli/src/
        language: system
        pass_filenames: false
